// RAC manager configuration.
// Replace only DEVICE_CODE with the 64-character code generated by the paired device.
const DEVICE_CODE = "PLACEHOLDER-CODE";

// Use "Desktop" for the desktop command window or "HomePhone" for the mobile terminal.
const DEVICE_TYPE = "Desktop";

module.exports = { DEVICE_CODE, DEVICE_TYPE };
