import argparse,platform,socket,time,uuid,subprocess,requests,re
from pathlib import Path

ALLOWED={"ping","lock","restart","shutdown"}
CODE_FILE=Path(__file__).with_name("code.js")

def load_device_code():
    text=CODE_FILE.read_text(encoding="utf-8")
    m=re.search(r'DEVICE_CODE\s*=\s*["\']([^"\']*)["\']', text)
    if not m or m.group(1)=="PLACEHOLDER-CODE":
        raise SystemExit("Pairing stopped: code.js still contains PLACEHOLDER-CODE. Put the 64-character code generated by the RAC controller into DEVICE_CODE.")
    code=m.group(1).strip()
    if not re.fullmatch(r"[0-9a-fA-F]{64}", code):
        raise SystemExit("Pairing stopped: DEVICE_CODE must be exactly 64 hexadecimal characters.")
    return code

def action(a):
    s=platform.system()
    if a=="ping": return True,"Agent is responding"
    if a=="lock":
        cmds={"Windows":[["rundll32.exe","user32.dll,LockWorkStation"]],"Linux":[["loginctl","lock-session"],["xdg-screensaver","lock"]],"Darwin":[["pmset","displaysleepnow"]]}.get(s,[])
    elif a=="restart": cmds=[["shutdown","/r","/t","5"]] if s=="Windows" else [["shutdown","-r","now"]]
    elif a=="shutdown": cmds=[["shutdown","/s","/t","5"]] if s=="Windows" else [["shutdown","-h","now"]]
    else:return False,"Action not allowed"
    for c in cmds:
        try: subprocess.run(c,check=False); return True,"Command sent"
        except FileNotFoundError: continue
    return False,"No supported command found"

def main():
    p=argparse.ArgumentParser(); p.add_argument("--controller",required=True); p.add_argument("--token",required=True); p.add_argument("--name",default=socket.gethostname()); a=p.parse_args()
    pair_code=load_device_code(); base=a.controller.rstrip("/"); h={"Authorization":f"Bearer {a.token}"}; did=str(uuid.uuid4())
    r=requests.post(base+"/api/enroll",json={"id":did,"code":pair_code,"name":a.name,"platform":platform.system(),"version":platform.release()},headers=h,timeout=10)
    r.raise_for_status(); print("Enrolled:",did)
    while True:
        try:
            requests.post(base+"/api/heartbeat",json={"id":did},headers=h,timeout=10)
            for c in requests.get(base+f"/api/commands/{did}",headers=h,timeout=10).json():
                ok,msg=action(c["action"]); requests.post(base+"/api/command-result",json={"device":did,"action":c["action"],"ok":ok,"message":msg},headers=h,timeout=10); print(c["action"],msg)
        except requests.RequestException as e: print("Controller unavailable:",e)
        time.sleep(3)
if __name__=="__main__": main()
